version: "3.8"

services:
  scraping:
    build: .
    container_name: scraping
    command: python scraping.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./.store:/app/.store

  fastapi-service:
    build: .
    container_name: fastapi-baseline
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./.store:/app/.store
    depends_on:
      scraping:
        condition: service_completed_successfully
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
